config/routes.rb
Rails.application.routes.draw do
  resources :payments

  resources :offline_payment_histories
  resources :offline_payments
  devise_for :users
  resources :plans
  resources :customers do 
    member do
      get :confirm_to_pay
    end
  end


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home, path: '/', only: :index do
    collection do
      get :home_1
      get :home_2
      post :create
      get :service
      get :pricing_plan
      get :about_us
      get :gallery
      get :faq
      get :blog_1
      get :blog_2
      get :blog_single
      get :contact
    end
  end
  match '/payu_callback' => 'customers#payu_return', :via => [:get, :post], :as => 'payments_payu_return'
  root 'home#index'
end

app/models/offline_payment.rb
class OfflinePayment < ApplicationRecord
  belongs_to :customer
  belongs_to :plan
  has_many :offline_payment_histories
end

app/controllers/offline_payments_controller.rb
class OfflinePaymentsController < InheritedResources::Base

	def create
		@offline_payment = OfflinePayment.new(offline_payment_params)
		@offline_payment.save
		redirect_to @offline_payment
	end

	def show
		@offline_payment  = OfflinePayment.find(params[:id])
	end

  private

    def offline_payment_params
      params.require(:offline_payment).permit(:cash, :check, :customer_id, :plan_id,:check_number,:bank_name)
    end
end

app/helpers/offline_payments_helper.rb
module OfflinePaymentsHelper
end

app/views/offline_payments/_form.html.erb
<%= form_for(offline_payment) do |f| %>
  <% if offline_payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offline_payment.errors.count, "error") %> prohibited this offline_payment from being saved:</h2>

      <ul>
      <% offline_payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cash %>
    <%= f.text_field :cash %>
  </div>

  <div class="field">
    <%= f.label :check %>
    <%= f.text_field :check %>
  </div>

  <div class="field">
    <%= f.label :customer_id %>
    <%= f.text_field :customer_id %>
  </div>

  <div class="field">
    <%= f.label :plan_id %>
    <%= f.text_field :plan_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offline_payments/edit.html.erb
<h1>Editing Offline Payment</h1>

<%= render 'form', offline_payment: @offline_payment %>

<%= link_to 'Show', @offline_payment %> |
<%= link_to 'Back', offline_payments_path %>

app/views/offline_payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offline Payments</h1>

<table>
  <thead>
    <tr>
      <th>Cash</th>
      <th>Check</th>
      <th>Customer</th>
      <th>Plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offline_payments.each do |offline_payment| %>
      <tr>
        <td><%= offline_payment.cash %></td>
        <td><%= offline_payment.check %></td>
        <td><%= offline_payment.customer %></td>
        <td><%= offline_payment.plan %></td>
        <td><%= link_to 'Show', offline_payment %></td>
        <td><%= link_to 'Edit', edit_offline_payment_path(offline_payment) %></td>
        <td><%= link_to 'Destroy', offline_payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offline Payment', new_offline_payment_path %>

app/views/offline_payments/new.html.erb
<h1>New Offline Payment</h1>

<%= render 'form', offline_payment: @offline_payment %>

<%= link_to 'Back', offline_payments_path %>

app/views/offline_payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cash:</strong>
  <%= @offline_payment.cash %>
</p>

<p>
  <strong>Check:</strong>
  <%= @offline_payment.check %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @offline_payment.customer %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @offline_payment.plan %>
</p>

<%= link_to 'Edit', edit_offline_payment_path(@offline_payment) %> |
<%= link_to 'Back', offline_payments_path %>