config/routes.rb
Rails.application.routes.draw do
  resources :payments

  resources :offline_payment_histories
  resources :offline_payments
  devise_for :users
  resources :plans
  resources :customers do 
    member do
      get :confirm_to_pay
    end
  end


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home, path: '/', only: :index do
    collection do
      get :home_1
      get :home_2
      post :create
      get :service
      get :pricing_plan
      get :about_us
      get :gallery
      get :faq
      get :blog_1
      get :blog_2
      get :blog_single
      get :contact
    end
  end
  match '/payu_callback' => 'customers#payu_return', :via => [:get, :post], :as => 'payments_payu_return'
  root 'home#index'
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :customer
  belongs_to :plan
  #after_save :create_payment_token

private
  #  def create_payment_token
  #   payment = Customer.new do |u|
  #     u.access_token = txnid
  #     u.save
  #   end

  # end
end

app/controllers/payments_controller.rb
class PaymentsController < InheritedResources::Base
  
  # all payment list of this customer
  def index
    @payments = Payment.all.order('created_at DESC')
  end
  
  private
    def payment_params
      params.require(:payment).permit(:mihpayid, :txnid, :status, :unmappedstatus, :amount, :cardCategory, :email, :name_on_card, :issuing_bank, :customer_id, :plan_id,:payment_mode)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(payment) do |f| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mihpayid %>
    <%= f.text_field :mihpayid %>
  </div>

  <div class="field">
    <%= f.label :txnid %>
    <%= f.text_field :txnid %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :unmappedstatus %>
    <%= f.text_field :unmappedstatus %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :cardCategory %>
    <%= f.text_field :cardCategory %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :name_on_card %>
    <%= f.text_field :name_on_card %>
  </div>

  <div class="field">
    <%= f.label :issuing_bank %>
    <%= f.text_field :issuing_bank %>
  </div>

  <div class="field">
    <%= f.label :customer_id %>
    <%= f.text_field :customer_id %>
  </div>

  <div class="field">
    <%= f.label :plan_id %>
    <%= f.text_field :plan_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Mihpayid</th>
      <th>Txnid</th>
      <th>Status</th>
      <th>Unmappedstatus</th>
      <th>Amount</th>
      <th>Cardcategory</th>
      <th>Email</th>
      <th>Name on card</th>
      <th>Issuing bank</th>
      <th>Customer</th>
      <th>Plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.mihpayid %></td>
        <td><%= payment.txnid %></td>
        <td><%= payment.status %></td>
        <td><%= payment.unmappedstatus %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.cardCategory %></td>
        <td><%= payment.email %></td>
        <td><%= payment.name_on_card %></td>
        <td><%= payment.issuing_bank %></td>
        <td><%= payment.customer %></td>
        <td><%= payment.plan %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mihpayid:</strong>
  <%= @payment.mihpayid %>
</p>

<p>
  <strong>Txnid:</strong>
  <%= @payment.txnid %>
</p>

<p>
  <strong>Status:</strong>
  <%= @payment.status %>
</p>

<p>
  <strong>Unmappedstatus:</strong>
  <%= @payment.unmappedstatus %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Cardcategory:</strong>
  <%= @payment.cardCategory %>
</p>

<p>
  <strong>Email:</strong>
  <%= @payment.email %>
</p>

<p>
  <strong>Name on card:</strong>
  <%= @payment.name_on_card %>
</p>

<p>
  <strong>Issuing bank:</strong>
  <%= @payment.issuing_bank %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @payment.customer %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @payment.plan %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>