config/routes.rb
Rails.application.routes.draw do
  resources :payments

  resources :offline_payment_histories
  resources :offline_payments
  devise_for :users
  resources :plans
  resources :customers do 
    member do
      get :confirm_to_pay
    end
  end


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home, path: '/', only: :index do
    collection do
      get :home_1
      get :home_2
      post :create
      get :service
      get :pricing_plan
      get :about_us
      get :gallery
      get :faq
      get :blog_1
      get :blog_2
      get :blog_single
      get :contact
    end
  end
  match '/payu_callback' => 'customers#payu_return', :via => [:get, :post], :as => 'payments_payu_return'
  root 'home#index'
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/controllers/plans_controller.rb
class PlansController < InheritedResources::Base

  private

    def plan_params
      params.require(:plan).permit(:plan_name,:plan_rate,:plan_price, :plan_start_date, :plan_expiry_date)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(plan) do |f| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plan_name %>
    <%= f.text_field :plan_name %>
  </div>

  <div class="field">
    <%= f.label :plan_price %>
    <%= f.text_field :plan_price %>
  </div>

  <div class="field">
    <%= f.label :plan_start_date %>
    <%= f.date_select :plan_start_date %>
  </div>

  <div class="field">
    <%= f.label :plan_expiry_date %>
    <%= f.date_select :plan_expiry_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Plan name</th>
      <th>Plan price</th>
      <th>Plan start date</th>
      <th>Plan expiry date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.plan_name %></td>
        <td><%= plan.plan_price %></td>
        <td><%= plan.plan_start_date %></td>
        <td><%= plan.plan_expiry_date %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plan name:</strong>
  <%= @plan.plan_name %>
</p>

<p>
  <strong>Plan price:</strong>
  <%= @plan.plan_price %>
</p>


<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>