config/routes.rb
Rails.application.routes.draw do
  resources :payments

  resources :offline_payment_histories
  resources :offline_payments
  devise_for :users
  resources :plans
  resources :customers do 
    member do
      get :confirm_to_pay
    end
  end


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home, path: '/', only: :index do
    collection do
      get :home_1
      get :home_2
      post :create
      get :service
      get :pricing_plan
      get :about_us
      get :gallery
      get :faq
      get :blog_1
      get :blog_2
      get :blog_single
      get :contact
    end
  end
  match '/payu_callback' => 'customers#payu_return', :via => [:get, :post], :as => 'payments_payu_return'
  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  
  has_many :payments
  belongs_to :plan
  
  validates :mobile_no, numericality: { only_integer: true }, length: \
          { minimum: 6, maximum: 11 }, allow_blank: true

  validates :phone_no, numericality: { only_integer: true }, length: \
          { minimum: 6, maximum: 11 }, allow_blank: true

  validates :address1, length: { in: 1..50 }, allow_blank: true
  validates :address2, length: { in: 1..50 }, allow_blank: true

  attr_accessor :file,:customer_id
  mount_uploader :file   
  has_many :customer_attachments, dependent: :destroy
  accepts_nested_attributes_for :customer_attachments
  after_save :create_user_account
  #before_create :set_access_token


private

 # def set_access_token
 #    self.access_token = SecureRandom.hex(10)
 #  end

 #  def generate_token
 #    loop do
 #      token = SecureRandom.hex(10)
 #      break token unless Customer.where(access_token: token).exists?
 #      Customer.update(access_token: token)
 #    end
 #  end

 def create_user_account
    user = User.new do |u|
      u.email = email
      u.password = customer_number
      u.save
    end

  end

end

app/models/customer_attachment.rb
class CustomerAttachment < ApplicationRecord
  belongs_to :customer
  mount_uploaders :file, FileUploader
end

app/models/home.rb
class Home < ApplicationRecord

	 attr_accessor :name, :email, :contact_no,:message

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :contact_no,
    presence: true

end

app/models/offline_payment.rb
class OfflinePayment < ApplicationRecord
  belongs_to :customer
  belongs_to :plan
  has_many :offline_payment_histories
end

app/models/offline_payment_history.rb
class OfflinePaymentHistory < ApplicationRecord
  belongs_to :customer
  belongs_to :plan
  belongs_to :offline_payment
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :customer
  belongs_to :plan
  #after_save :create_payment_token

private
  #  def create_payment_token
  #   payment = Customer.new do |u|
  #     u.access_token = txnid
  #     u.save
  #   end

  # end
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  after_create :send_signup_email


  def send_signup_email
    UserMailer.send_signup_email(self).deliver_now
  end

  def create_user_customer(customer_number,email)
    customer_number.each do |customer_number|
      UserCustomer.create(email: email, customer_number: customer_number)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = Home.new
  end

  def create

    @message = Home.new(home_params)

    if @message.valid?
      MessageMailer.new_message(@message).deliver_now
      flash.now[:notice] = "Your messages has been sent."
      else
      flash.now[:error] = "An error occurred while delivering this message."    
    render :new
    end
  end

  def home_1
  end

  def home_2
  end

  def service
  end

  def pricing_plan
  end

  def about_us
  end

  def gallery
  end

  def faq
  end

  def blog_1
  end

  def blog_2
  end

  def blog_single
  end

  def contact
    @message = Home.new
  end

private

def home_params
params.require(:home).permit!
end
end

app/controllers/offline_payment_histories_controller.rb
class OfflinePaymentHistoriesController < InheritedResources::Base

  private

    def offline_payment_history_params
      params.require(:offline_payment_history).permit(:customer_id, :plan_id, :cash, :check, :bank_name, :check_number, :amount_paid)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < InheritedResources::Base
  
  # all payment list of this customer
  def index
    @payments = Payment.all.order('created_at DESC')
  end
  
  private
    def payment_params
      params.require(:payment).permit(:mihpayid, :txnid, :status, :unmappedstatus, :amount, :cardCategory, :email, :name_on_card, :issuing_bank, :customer_id, :plan_id,:payment_mode)
    end
end

app/controllers/plans_controller.rb
class PlansController < InheritedResources::Base

  private

    def plan_params
      params.require(:plan).permit(:plan_name,:plan_rate,:plan_price, :plan_start_date, :plan_expiry_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        UserMailer.send_signup_email(@user).deliver_now
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offline_payment_histories_helper.rb
module OfflinePaymentHistoriesHelper
end

app/helpers/offline_payments_helper.rb
module OfflinePaymentsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/offline_payment_histories/_form.html.erb
<%= form_for(offline_payment_history) do |f| %>
  <% if offline_payment_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offline_payment_history.errors.count, "error") %> prohibited this offline_payment_history from being saved:</h2>

      <ul>
      <% offline_payment_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %>
    <%= f.text_field :customer_id %>
  </div>

  <div class="field">
    <%= f.label :plan_id %>
    <%= f.text_field :plan_id %>
  </div>

  <div class="field">
    <%= f.label :cash %>
    <%= f.text_field :cash %>
  </div>

  <div class="field">
    <%= f.label :check %>
    <%= f.text_field :check %>
  </div>

  <div class="field">
    <%= f.label :bank_name %>
    <%= f.text_field :bank_name %>
  </div>

  <div class="field">
    <%= f.label :check_number %>
    <%= f.text_field :check_number %>
  </div>

  <div class="field">
    <%= f.label :amount_paid %>
    <%= f.text_field :amount_paid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offline_payment_histories/edit.html.erb
<h1>Editing Offline Payment History</h1>

<%= render 'form', offline_payment_history: @offline_payment_history %>

<%= link_to 'Show', @offline_payment_history %> |
<%= link_to 'Back', offline_payment_histories_path %>

app/views/offline_payment_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offline Payment Histories</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Plan</th>
      <th>Cash</th>
      <th>Check</th>
      <th>Bank name</th>
      <th>Check number</th>
      <th>Amount paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offline_payment_histories.each do |offline_payment_history| %>
      <tr>
        <td><%= offline_payment_history.customer %></td>
        <td><%= offline_payment_history.plan %></td>
        <td><%= offline_payment_history.cash %></td>
        <td><%= offline_payment_history.check %></td>
        <td><%= offline_payment_history.bank_name %></td>
        <td><%= offline_payment_history.check_number %></td>
        <td><%= offline_payment_history.amount_paid %></td>
        <td><%= link_to 'Show', offline_payment_history %></td>
        <td><%= link_to 'Edit', edit_offline_payment_history_path(offline_payment_history) %></td>
        <td><%= link_to 'Destroy', offline_payment_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offline Payment History', new_offline_payment_history_path %>

app/views/offline_payment_histories/new.html.erb
<h1>New Offline Payment History</h1>

<%= render 'form', offline_payment_history: @offline_payment_history %>

<%= link_to 'Back', offline_payment_histories_path %>

app/views/offline_payment_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @offline_payment_history.customer %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @offline_payment_history.plan %>
</p>

<p>
  <strong>Cash:</strong>
  <%= @offline_payment_history.cash %>
</p>

<p>
  <strong>Check:</strong>
  <%= @offline_payment_history.check %>
</p>

<p>
  <strong>Bank name:</strong>
  <%= @offline_payment_history.bank_name %>
</p>

<p>
  <strong>Check number:</strong>
  <%= @offline_payment_history.check_number %>
</p>

<p>
  <strong>Amount paid:</strong>
  <%= @offline_payment_history.amount_paid %>
</p>

<%= link_to 'Edit', edit_offline_payment_history_path(@offline_payment_history) %> |
<%= link_to 'Back', offline_payment_histories_path %>